# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.TextField(blank=True, default='', null=True)),
                ('post', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('postid', models.IntegerField(blank=True, default=-1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=30)),
                ('rollno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('program', models.CharField(max_length=6)),
                ('department', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['firstname', '-updated', '-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
    ]
