# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='iscandidate',
            field=models.BooleanField(default=False),
        ),
    ]
