# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160406_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='postid',
        ),
    ]
