# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_candidate_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hasvoted',
            field=models.BooleanField(default=False),
        ),
    ]
