# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialkey', models.CharField(max_length=16)),
                ('general', models.IntegerField()),
                ('cultural', models.IntegerField()),
                ('technical', models.IntegerField()),
                ('sports', models.IntegerField()),
                ('environmental', models.IntegerField()),
                ('mess', models.IntegerField()),
                ('maintenance', models.IntegerField()),
                ('literary', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
