# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_hasvoted'),
        ('castvote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Candidate')),
            ],
            options={
                'ordering': ['candidate'],
            },
        ),
    ]
