# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castvote', '0002_candidatevotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storevote',
            name='specialkey',
            field=models.CharField(max_length=25),
        ),
    ]
