# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castvote', '0003_auto_20160416_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='storevote',
            name='year',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
